name: Build and Release

on:
    push:
        tags:
            - "v*"

jobs:
    build-and-release:
        permissions:
            contents: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Load .env file
              uses: xom9ikk/dotenv@v2
              with:
                  path: .devcontainer/

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ env.PYTHON_VERSION }}

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install build wheel

            - name: Build wheel
              run: |
                  python -m build

            - name: Create GitHub Release
              id: create_release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  tag: ${{ github.ref_name }}
              run: |
                  gh release create "$tag" \
                      --repo="$GITHUB_REPOSITORY" \
                      --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
                      --generate-notes

                  gh release upload "$tag" \
                      --repo="$GITHUB_REPOSITORY" \
                      ./dist/*.whl
